#!/usr/bin/env php
<?php

/**
 * RocketChat credentials
 */

$config = array(
  'hostname'  => 'localhost',
  'port'      => 3000,
  'userid'    => '1WseVrtjnH5HotLGG',
  'authtoken' => 'bQWEsKdEtPSSGJNjVvfT5BzYpP3KADFbjsy9vgTK802'
);

/**
 * Functions
 */

// Print munin configuration when args === "config"
function printMuninConfig(){
  print("graph_title RocketChat - user statistics" . PHP_EOL);
  print("graph_category rocketchat" . PHP_EOL);
  print("graph_vlabel Users" . PHP_EOL);
  print("graph_args --base 1000 -l 0" . PHP_EOL);
  print("total.type GAUGE" . PHP_EOL);
  print("total.label total users" . PHP_EOL);
  print("total.colour COLOUR8" . PHP_EOL);
  print("online.type GAUGE" . PHP_EOL);
  print("online.label online users" . PHP_EOL);
  print("online.colour COLOUR0" . PHP_EOL);
  print("away.type GAUGE" . PHP_EOL);
  print("away.label away users" . PHP_EOL);
  print("away.colour COLOUR2" . PHP_EOL);
  exit();
}

function getStatisticsFromApi(){
  global $config;
  $ch = curl_init();
  curl_setopt($ch, CURLOPT_URL, "http://" . $config['hostname'] . ":" . $config['port'] . "/api/v1/statistics?refresh=true");
  curl_setopt($ch, CURLOPT_HTTPHEADER, array(
    'X-User-Id: ' . $config['userid'],
    'X-Auth-Token: ' . $config['authtoken']
  ));

  curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
  $api = json_decode(curl_exec($ch));
  curl_close($ch);

  return $api;
}

/**
 * Logic
 */

if ((count($argv) > 1) && ($argv[1] === 'config')) {
  printMuninConfig();
}

$api = getStatisticsFromApi();

print('total.value ' . $api->statistics->totalUsers . "\n");
print('online.value ' . $api->statistics->onlineUsers . "\n");
print('away.value ' . $api->statistics->awayUsers . "\n");
