#!/usr/bin/env python3
import sys
import os
from rocketchat_API.rocketchat import RocketChat

rocketUser = os.getenv('user', 'user')
rocketPass = os.getenv('pass', 'pass')
rocketServer = os.getenv('server', 'http://localhost:3000')

def main(argv):
  if len(argv) == 2 and argv[1] == 'config':
    print("graph_title RocketChat - user statistics")
    print("graph_category rocketchat")
    print("graph_vlabel Users")
    print("total.type GAUGE")
    print("total.label total users")
    print("total.colour COLOUR8")
    print("online.type GAUGE")
    print("online.label online users")
    print("online.colour COLOUR0")
    print("away.type GAUGE")
    print("away.label away users")
    print("away.colour COLOUR2")
  else:
    rocketApi = RocketChat(rocketUser, rocketPass, server_url=rocketServer)
    response = rocketApi.statistics()

    print('total.value %d' % response.json()['totalUsers'])
    print('online.value %d' % response.json()['onlineUsers'])
    print('away.value %d' % response.json()['awayUsers'])
  return

if __name__ == "__main__":
  main(sys.argv)
